export const GET_SHUKKA_LIST = "GET_SHUKKA_LIST";
export const GET_COLUMN_LIST = "GET_COLUMN_LIST";
export const GET_SOUKO_LIST = "GET_SOUKO_LIST";
export const GET_SHUKKA_HEADER_ENTRY = "GET_SHUKKA_HEADER_ENTRY";
export const UPDATE_SHUKKA_HEADER_ENTRY = "UPDATE_SHUKKA_HEADER_ENTRY";
export const SHOW_MESSAGE_TOATS = "SHOW_MESSAGE_TOATS";
export const SHUKKA_SUCCESS = "SHUKKA_SUCCESS";
export const CLEAR_SHUKKA_LIST = "CLEAR_SHUKKA_LIST";